version: '3.8'

services:
  web:
    build: .
    pid: "host"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
      - DOCKER_API_VERSION=1.41
    env_file:
      - .env